export const models = [
  {
    id: 1,
    eria: "okayama",
    name: "Nozomi",
    pictures: ["/image/models/nozomi/nozomi-1.jpeg",
               "/image/models/nozomi/nozomi-2.jpeg"],
  },
  {
    id: 2,
    eria: "okayama",
    name: "ぐみちゃん",
    pictures: ["/image/models/gumi/gumi-1.jpeg",
               "/image/models/gumi/gumi-2.jpeg",
               "/image/models/gumi/gumi-3.jpeg",
               "/image/models/gumi/gumi-4.jpeg"],
  },
  {
    id: 3,
    eria: "kansai",
    name: "ちえり",
    pictures: ["/image/models/tieri/tieri-1.jpeg",
               "/image/models/tieri/tieri-3.jpeg"],
  },
  {
    id: 4,
    eria: "okayama",
    name: "りあ",
    pictures: ["/image/models/ria/ria-1.jpg"],
  },
  {
    id: 5,
    eria: "okayama",
    name: "ゆきち",
    pictures: ["/image/models/yukichi/yukichi-1.jpeg"],
  },
  {
    id: 6,
    eria: "okayama",
    name: "みあ",
    pictures: ["/image/models/mia/mia-1.jpeg"],
  },
  {
    id: 7,
    eria: "okayama",
    name: "kanako",
    pictures: ["/image/models/kanako/kanako-1.jpeg",
               "/image/models/kanako/kanako-2.jpeg",
               "/image/models/kanako/kanako-3.jpeg",
               "/image/models/kanako/kanako-4.jpeg",
               "/image/models/kanako/kanako-5.jpeg"],
  },
  {
    id: 8,
    eria: "okayama",
    name: "れいな",
    pictures: ["/image/models/reina/reina-1.jpeg",
               "/image/models/reina/reina-2.jpeg"],
  },
  {
    id: 9,
    eria: "okayama",
    name: "Kotone",
    pictures: ["/image/models/kotone/kotone-1.jpeg",
               "/image/models/kotone/kotone-2.jpeg",
               "/image/models/kotone/kotone-3.jpeg",
               "/image/models/kotone/kotone-4.jpeg",
               "/image/models/kotone/kotone-5.jpeg",
               "/image/models/kotone/kotone-6.jpeg"],
  },
  {
    id: 10,
    eria: "okayama",
    name: "Rina",
    pictures: ["/image/models/rina/rina-1.jpeg",
               "/image/models/rina/rina-2.jpeg",
               "/image/models/rina/rina-3.jpeg",
               "/image/models/rina/rina-4.jpeg",
               "/image/models/rina/rina-5.jpeg"],
  },
  {
    id: 11,
    eria: "okayama",
    name: "羽花",
    pictures: ["/image/models/waka/waka-1.jpeg",
               "/image/models/waka/waka-2.jpeg",
               "/image/models/waka/waka-3.jpeg",
               "/image/models/waka/waka-4.jpeg"],
  },
  {
    id: 12,
    eria: "okayama",
    name: "ゆづ",
    pictures: ["/image/models/yudu/yudu-1.jpeg",
               "/image/models/yudu/yudu-2.jpeg",
               "/image/models/yudu/yudu-3.jpeg",
               "/image/models/yudu/yudu-4.jpeg"],
  },
  {
    id: 13,
    eria: "okayama",
    name: "さぁちゃん",
    pictures: ["/image/models/saxatyan/saxatyan-1.jpeg",
               "/image/models/saxatyan/saxatyan-2.jpeg",
               "/image/models/saxatyan/saxatyan-3.jpeg",
               "/image/models/saxatyan/saxatyan-4.jpeg",
               "/image/models/saxatyan/saxatyan-5.jpeg",
               "/image/models/saxatyan/saxatyan-6.jpeg"],
  },
  {
    id: 14,
    eria: "okayama",
    name: "aya",
    pictures: ["/image/models/aya/aya-1.jpeg",
               "/image/models/aya/aya-2.jpeg",
               "/image/models/aya/aya-3.jpeg",
               "/image/models/aya/aya-4.jpeg",
               "/image/models/aya/aya-5.jpeg",
               "/image/models/aya/aya-6.jpeg",
               "/image/models/aya/aya-7.jpeg"],
  },
  {
    id: 15,
    eria: "okayama",
    name: "ももか",
    pictures: ["/image/models/momoka/momoka-1.jpeg",
               "/image/models/momoka/momoka-2.jpeg",
               "/image/models/momoka/momoka-3.jpeg",
               "/image/models/momoka/momoka-4.jpeg"],
  },
  {
    id: 16,
    eria: "okayama",
    name: "Rei",
    pictures: ["/image/models/rei/rei-1.jpeg",
               "/image/models/rei/rei-2.jpeg",
               "/image/models/rei/rei-3.jpeg",
               "/image/models/rei/rei-4.jpeg"],
  },
  {
    id: 17,
    eria: "okayama",
    name: "ちえ",
    pictures: ["/image/models/tie/tie-1.jpeg",
               "/image/models/tie/tie-2.jpeg",
               "/image/models/tie/tie-3.jpeg",
               "/image/models/tie/tie-4.jpeg",
               "/image/models/tie/tie-5.jpeg"],
  },
  {
    id: 18,
    eria: "okayama",
    name: "もと",
    pictures: ["/image/models/moto/moto-1.jpeg",
               "/image/models/moto/moto-2.jpeg",
               "/image/models/moto/moto-3.jpeg",
               "/image/models/moto/moto-4.jpeg",
               "/image/models/moto/moto-5.jpeg"],
  },
  {
    id: 19,
    eria: "okayama",
    name: "sho",
    pictures: ["/image/models/sho/sho-1.jpeg",
               "/image/models/sho/sho-2.jpeg",
               "/image/models/sho/sho-3.jpeg",
               "/image/models/sho/sho-4.jpeg",
               "/image/models/sho/sho-5.jpeg"],
  },
]
// one-flash/public/image/models/tieri-1.jpeg